### ISSUE TITLE
Question about the "Implementation of the Turing machine prototype."

### ISSUE THREAD

**Issue by Xuchen-Li** [NJUDeepEngine/CAEF#1]
Hello,

Thank you for your insightful paper. I’ve been particularly intrigued by the section discussing the limitations, where you mention:

"A practical approach is to construct a Turing machine prototype corresponding to the target operator and record its execution process. While there are many existing Turing machine designs, the implementation process may take some human-involved effort. A future work could design a generation process to translate existing Turing machines into CAEF required Turing machine prototypes."

I would greatly appreciate it if you could elaborate on the following points:

Why do we need a practical approach to construct a Turing machine prototype corresponding to the target operator and record its execution process? I think it is possible to implement a general finite state machine to achieve the functionality of each operator. Where lies the necessity of a dedicated finite state machine?

Thank you in advance for your time and clarification. I look forward to your response.

Best regards,
Xuchen Li

**Comment by Edmund-Lai** [comment]
Hello,

Thank you for your thoughtful questions and for engaging with our paper in such detail. You raise a very valid point regarding the use of a general finite state machine to implement the functionality of each operator. In fact, at the early stage, our intention was to design a model based on the idea of universal Turing machine that could handle all operators. Ideally, our ultimate vision is to use one model to handle all operators. However, during the implementation phase, we encountered two key challenges that led us to adopt the current approach:

1. **Scalability with Operators**: If the number of operators is fixed—such as the seven mentioned in the paper—this method is indeed feasible. However, if we were to introduce additional operators (for instance, exponential or logarithmic functions), the trained model would need to be retrained. Moreover, training a model based on the existing one can run into the issue of catastrophic forgetting, where previously learned operators might degrade in performance.

2. **Implementation Complexity**: We have currently employed LoRA, a relatively lightweight fine-tuning method. Assigning all the operator functionalities to a single LoRA adapter would be quite challenging. Full model fine-tuning might offer a solution, but we have not tried it yet.

I hope this clarifies our decision-making process. Please feel free to reach out if you have further questions or thoughts!

Best regards

**Comment by Xuchen-Li** [comment]
Thank you very much for taking the time to respond to my question. Your reply was not only detailed but also contained many insightful analyses.
I just ran a simple test without giving much thought to the issues within the training process. I will continue to follow your paper. Thank you again!

Best regards
